Система авиаперевозок (C++): Schedule Class Reference
Schedule Class Reference
Расписание: список рейсов, упорядоченный по времени вылета; проверка конфликтов и корректности.
#include <Schedule.h>
Public Member Functions
Schedule ()
Schedule (const Schedule &other)
Schedule & operator= (const Schedule &other)
~Schedule ()
void addFlight (std::shared_ptr< Flight > flight)
Добавить рейс в расписание
void removeFlight (const std::string &flightNumber)
Удалить рейс из расписания
std::shared_ptr< Flight > findFlight (const std::string &flightNumber) const
Найти рейс по номеру
bool isValid () const
Проверить корректность расписания
std::vector< std::string > getValidationErrors () const
Получить список ошибок валидации
void validateAndFix ()
Проверить и исправить ошибки в расписании
const std::vector< std::shared_ptr< Flight > > & getFlights () const
Получить список всех рейсов
std::vector< std::shared_ptr< Flight > > getFlightsByAircraft (const std::string &aircraftId) const
Получить рейсы самолёта
std::vector< std::shared_ptr< Flight > > getFlightsByAirport (const std::string &airportCode) const
Получить рейсы аэропорта
std::vector< std::shared_ptr< Flight > > getFlightsInTimeRange (std::time_t startTime, std::time_t endTime) const
Получить рейсы в временном диапазоне
double getTotalFlightTime (const std::string &aircraftId) const
Получить общее время полётов самолёта
double getTotalFlightTimeInRange (const std::string &aircraftId, std::time_t startTime, std::time_t endTime) const
Получить время полётов в диапазоне
std::vector< std::string > getOverworkedAircraft () const
Получить список перегруженных самолётов
std::string toString () const
Получить строковое представление всего расписания
std::string getScheduleForAircraft (const std::string &aircraftId) const
Получить расписание для самолёта
std::string getScheduleForAircraftInRange (const std::string &aircraftId, std::time_t startTime, std::time_t endTime) const
Получить расписание самолёта в диапазоне
std::string getOverdueUrgentCargoReport () const
Получить отчёт о просроченных срочных грузах
void completeFlight (const std::string &flightNumber)
Завершить рейс
void addReturnFlights ()
Добавить обратные рейсы для всех прямых рейсов
int getTotalFlights () const
Получить общее количество рейсов
int getCompletedFlights () const
Получить количество завершённых рейсов
int getScheduledFlights () const
Получить количество запланированных рейсов
int getInProgressFlights () const
Получить количество рейсов в процессе
Detailed Description
Расписание: список рейсов, упорядоченный по времени вылета; проверка конфликтов и корректности.
Definition at line 14 of file Schedule.h.
Constructor & Destructor Documentation
Schedule() [1/2]
Schedule::Schedule ()
Definition at line 9 of file Schedule.cpp.
Referenced by operator=(), and Schedule().
Schedule() [2/2]
Schedule::Schedule (const Schedule & other)
Definition at line 13 of file Schedule.cpp.
~Schedule()
Schedule::~Schedule ()
Definition at line 25 of file Schedule.cpp.
Member Function Documentation
addFlight()
void Schedule::addFlight (std::shared_ptr< Flight > flight)
Добавить рейс в расписание
Definition at line 30 of file Schedule.cpp.
Referenced by addReturnFlights().
addReturnFlights()
void Schedule::addReturnFlights ()
Добавить обратные рейсы для всех прямых рейсов
Definition at line 317 of file Schedule.cpp.
completeFlight()
void Schedule::completeFlight (const std::string & flightNumber)
Завершить рейс
Definition at line 309 of file Schedule.cpp.
findFlight()
std::shared_ptr< Flight > Schedule::findFlight (const std::string & flightNumber) const
Найти рейс по номеру
Definition at line 49 of file Schedule.cpp.
Referenced by completeFlight(), and Schedule_FindFlight().
getCompletedFlights()
int Schedule::getCompletedFlights () const
Получить количество завершённых рейсов
Definition at line 339 of file Schedule.cpp.
getFlights()
const std::vector< std::shared_ptr< Flight > > & Schedule::getFlights () const
Получить список всех рейсов
Definition at line 132 of file Schedule.cpp.
getFlightsByAircraft()
std::vector< std::shared_ptr< Flight > > Schedule::getFlightsByAircraft (const std::string & aircraftId) const
Получить рейсы самолёта
Definition at line 137 of file Schedule.cpp.
Referenced by getScheduleForAircraft(), and getScheduleForAircraftInRange().
getFlightsByAirport()
std::vector< std::shared_ptr< Flight > > Schedule::getFlightsByAirport (const std::string & airportCode) const
Получить рейсы аэропорта
Definition at line 150 of file Schedule.cpp.
getFlightsInTimeRange()
std::vector< std::shared_ptr< Flight > > Schedule::getFlightsInTimeRange (std::time_t startTime, std::time_t endTime) const
Получить рейсы в временном диапазоне
Definition at line 164 of file Schedule.cpp.
getInProgressFlights()
int Schedule::getInProgressFlights () const
Получить количество рейсов в процессе
Definition at line 361 of file Schedule.cpp.
getOverdueUrgentCargoReport()
std::string Schedule::getOverdueUrgentCargoReport () const
Получить отчёт о просроченных срочных грузах
Definition at line 298 of file Schedule.cpp.
Referenced by Schedule_GetOverdueUrgentCargoReport().
getOverworkedAircraft()
std::vector< std::string > Schedule::getOverworkedAircraft () const
Получить список перегруженных самолётов
Definition at line 206 of file Schedule.cpp.
getScheduledFlights()
int Schedule::getScheduledFlights () const
Получить количество запланированных рейсов
Definition at line 350 of file Schedule.cpp.
getScheduleForAircraft()
std::string Schedule::getScheduleForAircraft (const std::string & aircraftId) const
Получить расписание для самолёта
Definition at line 258 of file Schedule.cpp.
Referenced by Schedule_GetScheduleForAircraft().
getScheduleForAircraftInRange()
std::string Schedule::getScheduleForAircraftInRange (const std::string & aircraftId, std::time_t startTime, std::time_t endTime) const
Получить расписание самолёта в диапазоне
Definition at line 278 of file Schedule.cpp.
Referenced by Schedule_GetScheduleForAircraftInRange().
getTotalFlights()
int Schedule::getTotalFlights () const
Получить общее количество рейсов
Definition at line 334 of file Schedule.cpp.
Referenced by Schedule_GetTotalFlights().
getTotalFlightTime()
double Schedule::getTotalFlightTime (const std::string & aircraftId) const
Получить общее время полётов самолёта
Definition at line 178 of file Schedule.cpp.
Referenced by Schedule_GetTotalFlightTime().
getTotalFlightTimeInRange()
double Schedule::getTotalFlightTimeInRange (const std::string & aircraftId, std::time_t startTime, std::time_t endTime) const
Получить время полётов в диапазоне
Definition at line 191 of file Schedule.cpp.
getValidationErrors()
std::vector< std::string > Schedule::getValidationErrors () const
Получить список ошибок валидации
Definition at line 93 of file Schedule.cpp.
Referenced by Schedule_GetValidationErrors().
isValid()
bool Schedule::isValid () const
Проверить корректность расписания
Definition at line 80 of file Schedule.cpp.
Referenced by Schedule_IsValid().
operator=()
Schedule & Schedule::operator= (const Schedule & other)
Definition at line 17 of file Schedule.cpp.
removeFlight()
void Schedule::removeFlight (const std::string & flightNumber)
Удалить рейс из расписания
Definition at line 38 of file Schedule.cpp.
Referenced by Schedule_RemoveFlight().
toString()
std::string Schedule::toString () const
Получить строковое представление всего расписания
Definition at line 243 of file Schedule.cpp.
Referenced by Schedule_ToString().
validateAndFix()
void Schedule::validateAndFix ()
Проверить и исправить ошибки в расписании
Definition at line 117 of file Schedule.cpp.
Referenced by Schedule_ValidateAndFix().
The documentation for this class was generated from the following files:
include/Schedule.h
src/Schedule.cpp