Система авиаперевозок (C++): Cargo Class Reference
Cargo Class Reference
Базовый класс для представления груза (номер, масса, аэропорты, время прибытия).
#include <Cargo.h>
Public Member Functions
Cargo ()
Cargo (const std::string &number, double cargoMass, const std::string &departure, const std::string &destination, const std::string &current, std::time_t arrival)
конструктор по умолчанию
Cargo (const Cargo &other)
Cargo & operator= (const Cargo &other)
~Cargo ()
std::string getCargoNumber () const
деструктор
double getMass () const
std::string getDepartureAirport () const
std::string getDestinationAirport () const
std::string getCurrentAirport () const
std::time_t getArrivalTime () const
void setCargoNumber (const std::string &number)
void setMass (double cargoMass)
void setDepartureAirport (const std::string &departure)
void setDestinationAirport (const std::string &destination)
void setCurrentAirport (const std::string &current)
void setArrivalTime (std::time_t arrival)
bool operator== (const Cargo &other) const
bool operator!= (const Cargo &other) const
bool operator< (const Cargo &other) const
bool operator<= (const Cargo &other) const
bool operator> (const Cargo &other) const
bool operator>= (const Cargo &other) const
void moveToAirport (const std::string &newAirport)
bool hasReachedDestination () const
virtual std::string toString () const
virtual bool isValid () const
Detailed Description
Базовый класс для представления груза (номер, масса, аэропорты, время прибытия).
Definition at line 12 of file Cargo.h.
Constructor & Destructor Documentation
Cargo() [1/3]
Cargo::Cargo ()
Definition at line 7 of file Cargo.cpp.
Referenced by Cargo(), operator!=(), operator<(), operator<=(), operator=(), operator==(), operator>(), operator>=(), UrgentCargo::UrgentCargo(), UrgentCargo::UrgentCargo(), UrgentCargo::UrgentCargo(), and UrgentCargo::UrgentCargo().
Cargo() [2/3]
Cargo::Cargo (const std::string & number, double cargoMass, const std::string & departure, const std::string & destination, const std::string & current, std::time_t arrival)
конструктор по умолчанию
Definition at line 13 of file Cargo.cpp.
Cargo() [3/3]
Cargo::Cargo (const Cargo & other)
Definition at line 21 of file Cargo.cpp.
~Cargo()
Cargo::~Cargo ()
Definition at line 41 of file Cargo.cpp.
Member Function Documentation
getArrivalTime()
std::time_t Cargo::getArrivalTime () const
Definition at line 66 of file Cargo.cpp.
getCargoNumber()
std::string Cargo::getCargoNumber () const
деструктор
Definition at line 46 of file Cargo.cpp.
Referenced by Cargo_GetCargoNumber().
getCurrentAirport()
std::string Cargo::getCurrentAirport () const
Definition at line 62 of file Cargo.cpp.
getDepartureAirport()
std::string Cargo::getDepartureAirport () const
Definition at line 54 of file Cargo.cpp.
getDestinationAirport()
std::string Cargo::getDestinationAirport () const
Definition at line 58 of file Cargo.cpp.
getMass()
double Cargo::getMass () const
Definition at line 50 of file Cargo.cpp.
Referenced by Cargo_GetMass().
hasReachedDestination()
bool Cargo::hasReachedDestination () const
Definition at line 126 of file Cargo.cpp.
isValid()
bool Cargo::isValid () const virtual
Reimplemented in UrgentCargo.
Definition at line 160 of file Cargo.cpp.
Referenced by UrgentCargo::isValid().
moveToAirport()
void Cargo::moveToAirport (const std::string & newAirport)
Definition at line 121 of file Cargo.cpp.
operator!=()
bool Cargo::operator!= (const Cargo & other) const
Definition at line 100 of file Cargo.cpp.
operator<()
bool Cargo::operator< (const Cargo & other) const
Definition at line 104 of file Cargo.cpp.
operator<=()
bool Cargo::operator<= (const Cargo & other) const
Definition at line 108 of file Cargo.cpp.
operator=()
Cargo & Cargo::operator= (const Cargo & other)
Definition at line 28 of file Cargo.cpp.
Referenced by UrgentCargo::operator=().
operator==()
bool Cargo::operator== (const Cargo & other) const
Definition at line 96 of file Cargo.cpp.
Referenced by UrgentCargo::operator==().
operator>()
bool Cargo::operator> (const Cargo & other) const
Definition at line 112 of file Cargo.cpp.
operator>=()
bool Cargo::operator>= (const Cargo & other) const
Definition at line 116 of file Cargo.cpp.
setArrivalTime()
void Cargo::setArrivalTime (std::time_t arrival)
Definition at line 91 of file Cargo.cpp.
setCargoNumber()
void Cargo::setCargoNumber (const std::string & number)
Definition at line 71 of file Cargo.cpp.
setCurrentAirport()
void Cargo::setCurrentAirport (const std::string & current)
Definition at line 87 of file Cargo.cpp.
setDepartureAirport()
void Cargo::setDepartureAirport (const std::string & departure)
Definition at line 79 of file Cargo.cpp.
setDestinationAirport()
void Cargo::setDestinationAirport (const std::string & destination)
Definition at line 83 of file Cargo.cpp.
setMass()
void Cargo::setMass (double cargoMass)
Definition at line 75 of file Cargo.cpp.
toString()
std::string Cargo::toString () const virtual
Reimplemented in UrgentCargo.
Definition at line 131 of file Cargo.cpp.
Referenced by Cargo_ToString(), and UrgentCargo::toString().
The documentation for this class was generated from the following files:
include/Cargo.h
src/Cargo.cpp