Система авиаперевозок (C++): UrgentCargo Class Reference
UrgentCargo Class Reference
Срочный груз: крайний срок доставки; методы isOverdue(), isUrgent(), getDaysUntilDeadline().
#include <UrgentCargo.h>
Public Member Functions
UrgentCargo ()
UrgentCargo (const std::string &number, double cargoMass, const std::string &departure, const std::string &destination, const std::string &current, std::time_t arrival, std::time_t deadline)
UrgentCargo (const UrgentCargo &other)
UrgentCargo (const Cargo &cargo, std::time_t deadline)
UrgentCargo & operator= (const UrgentCargo &other)
~UrgentCargo ()
std::time_t getDeadline () const
void setDeadline (std::time_t deadline)
bool isOverdue () const
Проверить, просрочен ли груз
bool isUrgent () const
Проверить, является ли груз срочным
int getDaysUntilDeadline () const
Получить количество дней до крайнего срока
std::string toString () const override
bool isValid () const override
bool operator== (const UrgentCargo &other) const
bool operator!= (const UrgentCargo &other) const
bool operator< (const UrgentCargo &other) const
bool operator<= (const UrgentCargo &other) const
bool operator> (const UrgentCargo &other) const
bool operator>= (const UrgentCargo &other) const
Public Member Functions inherited from Cargo
Cargo ()
Cargo (const std::string &number, double cargoMass, const std::string &departure, const std::string &destination, const std::string &current, std::time_t arrival)
конструктор по умолчанию
Cargo (const Cargo &other)
Cargo & operator= (const Cargo &other)
~Cargo ()
std::string getCargoNumber () const
деструктор
double getMass () const
std::string getDepartureAirport () const
std::string getDestinationAirport () const
std::string getCurrentAirport () const
std::time_t getArrivalTime () const
void setCargoNumber (const std::string &number)
void setMass (double cargoMass)
void setDepartureAirport (const std::string &departure)
void setDestinationAirport (const std::string &destination)
void setCurrentAirport (const std::string &current)
void setArrivalTime (std::time_t arrival)
bool operator== (const Cargo &other) const
bool operator!= (const Cargo &other) const
bool operator< (const Cargo &other) const
bool operator<= (const Cargo &other) const
bool operator> (const Cargo &other) const
bool operator>= (const Cargo &other) const
void moveToAirport (const std::string &newAirport)
bool hasReachedDestination () const
Detailed Description
Срочный груз: крайний срок доставки; методы isOverdue(), isUrgent(), getDaysUntilDeadline().
Definition at line 11 of file UrgentCargo.h.
Constructor & Destructor Documentation
UrgentCargo() [1/4]
UrgentCargo::UrgentCargo ()
Definition at line 7 of file UrgentCargo.cpp.
Referenced by operator!=(), operator<(), operator<=(), operator=(), operator==(), operator>(), operator>=(), and UrgentCargo().
UrgentCargo() [2/4]
UrgentCargo::UrgentCargo (const std::string & number, double cargoMass, const std::string & departure, const std::string & destination, const std::string & current, std::time_t arrival, std::time_t deadline)
Definition at line 11 of file UrgentCargo.cpp.
UrgentCargo() [3/4]
UrgentCargo::UrgentCargo (const UrgentCargo & other)
Definition at line 18 of file UrgentCargo.cpp.
UrgentCargo() [4/4]
UrgentCargo::UrgentCargo (const Cargo & cargo, std::time_t deadline)
Definition at line 23 of file UrgentCargo.cpp.
~UrgentCargo()
UrgentCargo::~UrgentCargo ()
Definition at line 37 of file UrgentCargo.cpp.
Member Function Documentation
getDaysUntilDeadline()
int UrgentCargo::getDaysUntilDeadline () const
Получить количество дней до крайнего срока
Definition at line 68 of file UrgentCargo.cpp.
getDeadline()
std::time_t UrgentCargo::getDeadline () const
Definition at line 42 of file UrgentCargo.cpp.
isOverdue()
bool UrgentCargo::isOverdue () const
Проверить, просрочен ли груз
Definition at line 51 of file UrgentCargo.cpp.
Referenced by toString(), and UrgentCargo_IsOverdue().
isUrgent()
bool UrgentCargo::isUrgent () const
Проверить, является ли груз срочным
Definition at line 59 of file UrgentCargo.cpp.
Referenced by toString().
isValid()
bool UrgentCargo::isValid () const override virtual
Reimplemented from Cargo.
Definition at line 102 of file UrgentCargo.cpp.
operator!=()
bool UrgentCargo::operator!= (const UrgentCargo & other) const
Definition at line 127 of file UrgentCargo.cpp.
operator<()
bool UrgentCargo::operator< (const UrgentCargo & other) const
Definition at line 131 of file UrgentCargo.cpp.
operator<=()
bool UrgentCargo::operator<= (const UrgentCargo & other) const
Definition at line 138 of file UrgentCargo.cpp.
operator=()
UrgentCargo & UrgentCargo::operator= (const UrgentCargo & other)
Definition at line 28 of file UrgentCargo.cpp.
operator==()
bool UrgentCargo::operator== (const UrgentCargo & other) const
Definition at line 123 of file UrgentCargo.cpp.
operator>()
bool UrgentCargo::operator> (const UrgentCargo & other) const
Definition at line 142 of file UrgentCargo.cpp.
operator>=()
bool UrgentCargo::operator>= (const UrgentCargo & other) const
Definition at line 146 of file UrgentCargo.cpp.
setDeadline()
void UrgentCargo::setDeadline (std::time_t deadline)
Definition at line 46 of file UrgentCargo.cpp.
toString()
std::string UrgentCargo::toString () const override virtual
Reimplemented from Cargo.
Definition at line 80 of file UrgentCargo.cpp.
Referenced by UrgentCargo_ToString().
The documentation for this class was generated from the following files:
include/UrgentCargo.h
src/UrgentCargo.cpp