Система авиаперевозок (C++): Flight Class Reference
Flight Class Reference
Рейс: номер, аэропорты отправления/назначения, время вылета/прилёта, ID самолёта, флаг завершения.
#include <Flight.h>
Public Member Functions
Flight ()
Flight (const std::string &number, const std::string &departure, const std::string &destination, std::time_t depTime, std::time_t arrTime, const std::string &aircraft)
Flight (const Flight &other)
Flight & operator= (const Flight &other)
~Flight ()
std::string getFlightNumber () const
std::string getDepartureAirport () const
std::string getDestinationAirport () const
std::time_t getDepartureTime () const
std::time_t getArrivalTime () const
std::string getAircraftId () const
bool isCompleted () const
void setFlightNumber (const std::string &number)
void setDepartureAirport (const std::string &departure)
void setDestinationAirport (const std::string &destination)
void setDepartureTime (std::time_t depTime)
void setArrivalTime (std::time_t arrTime)
void setAircraftId (const std::string &aircraft)
void setCompleted (bool completed)
std::time_t getFlightDuration () const
Получить продолжительность рейса в секундах
double getFlightDurationHours () const
Получить продолжительность рейса в часах
bool isInProgress () const
Проверить, идёт ли рейс сейчас
bool isScheduled () const
Проверить, запланирован ли рейс
void completeFlight ()
Завершить рейс
Flight createReturnFlight () const
Создать обратный рейс
std::string getReturnFlightNumber () const
Получить номер обратного рейса
void unloadCargoAndPassengers (std::shared_ptr< Aircraft > aircraft) const
Выгрузить грузы и пассажиров по прибытии
std::string toString () const
Получить строковое представление
bool isValid () const
Проверить корректность данных
bool conflictsWith (const Flight &other) const
Проверить конфликт с другим рейсом
bool operator== (const Flight &other) const
bool operator!= (const Flight &other) const
bool operator< (const Flight &other) const
bool operator<= (const Flight &other) const
bool operator> (const Flight &other) const
bool operator>= (const Flight &other) const
Detailed Description
Рейс: номер, аэропорты отправления/назначения, время вылета/прилёта, ID самолёта, флаг завершения.
Definition at line 13 of file Flight.h.
Constructor & Destructor Documentation
Flight() [1/3]
Flight::Flight ()
Definition at line 7 of file Flight.cpp.
Referenced by conflictsWith(), createReturnFlight(), Flight(), operator!=(), operator<(), operator<=(), operator=(), operator==(), operator>(), and operator>=().
Flight() [2/3]
Flight::Flight (const std::string & number, const std::string & departure, const std::string & destination, std::time_t depTime, std::time_t arrTime, const std::string & aircraft)
Definition at line 13 of file Flight.cpp.
Flight() [3/3]
Flight::Flight (const Flight & other)
Definition at line 21 of file Flight.cpp.
~Flight()
Flight::~Flight ()
Definition at line 42 of file Flight.cpp.
Member Function Documentation
completeFlight()
void Flight::completeFlight ()
Завершить рейс
Definition at line 134 of file Flight.cpp.
conflictsWith()
bool Flight::conflictsWith (const Flight & other) const
Проверить конфликт с другим рейсом
Definition at line 235 of file Flight.cpp.
createReturnFlight()
Flight Flight::createReturnFlight () const
Создать обратный рейс
Definition at line 139 of file Flight.cpp.
Referenced by Schedule::addReturnFlights().
getAircraftId()
std::string Flight::getAircraftId () const
Definition at line 67 of file Flight.cpp.
Referenced by Flight_GetAircraftId().
getArrivalTime()
std::time_t Flight::getArrivalTime () const
Definition at line 63 of file Flight.cpp.
getDepartureAirport()
std::string Flight::getDepartureAirport () const
Definition at line 51 of file Flight.cpp.
Referenced by Flight_GetDepartureAirport().
getDepartureTime()
std::time_t Flight::getDepartureTime () const
Definition at line 59 of file Flight.cpp.
Referenced by createReturnFlight().
getDestinationAirport()
std::string Flight::getDestinationAirport () const
Definition at line 55 of file Flight.cpp.
Referenced by Flight_GetDestinationAirport().
getFlightDuration()
std::time_t Flight::getFlightDuration () const
Получить продолжительность рейса в секундах
Definition at line 105 of file Flight.cpp.
Referenced by createReturnFlight(), and getFlightDurationHours().
getFlightDurationHours()
double Flight::getFlightDurationHours () const
Получить продолжительность рейса в часах
Definition at line 113 of file Flight.cpp.
Referenced by Flight_GetFlightDurationHours(), and toString().
getFlightNumber()
std::string Flight::getFlightNumber () const
Definition at line 47 of file Flight.cpp.
Referenced by Flight_GetFlightNumber().
getReturnFlightNumber()
std::string Flight::getReturnFlightNumber () const
Получить номер обратного рейса
Definition at line 160 of file Flight.cpp.
Referenced by createReturnFlight().
isCompleted()
bool Flight::isCompleted () const
Definition at line 71 of file Flight.cpp.
Referenced by Flight_IsCompleted().
isInProgress()
bool Flight::isInProgress () const
Проверить, идёт ли рейс сейчас
Definition at line 118 of file Flight.cpp.
Referenced by toString().
isScheduled()
bool Flight::isScheduled () const
Проверить, запланирован ли рейс
Definition at line 126 of file Flight.cpp.
Referenced by toString().
isValid()
bool Flight::isValid () const
Проверить корректность данных
Definition at line 214 of file Flight.cpp.
Referenced by Flight_IsValid().
operator!=()
bool Flight::operator!= (const Flight & other) const
Definition at line 251 of file Flight.cpp.
operator<()
bool Flight::operator< (const Flight & other) const
Definition at line 255 of file Flight.cpp.
operator<=()
bool Flight::operator<= (const Flight & other) const
Definition at line 259 of file Flight.cpp.
operator=()
Flight & Flight::operator= (const Flight & other)
Definition at line 28 of file Flight.cpp.
operator==()
bool Flight::operator== (const Flight & other) const
Definition at line 247 of file Flight.cpp.
operator>()
bool Flight::operator> (const Flight & other) const
Definition at line 263 of file Flight.cpp.
operator>=()
bool Flight::operator>= (const Flight & other) const
Definition at line 267 of file Flight.cpp.
setAircraftId()
void Flight::setAircraftId (const std::string & aircraft)
Definition at line 96 of file Flight.cpp.
Referenced by createReturnFlight().
setArrivalTime()
void Flight::setArrivalTime (std::time_t arrTime)
Definition at line 92 of file Flight.cpp.
Referenced by createReturnFlight().
setCompleted()
void Flight::setCompleted (bool completed)
Definition at line 100 of file Flight.cpp.
setDepartureAirport()
void Flight::setDepartureAirport (const std::string & departure)
Definition at line 80 of file Flight.cpp.
Referenced by createReturnFlight().
setDepartureTime()
void Flight::setDepartureTime (std::time_t depTime)
Definition at line 88 of file Flight.cpp.
Referenced by createReturnFlight().
setDestinationAirport()
void Flight::setDestinationAirport (const std::string & destination)
Definition at line 84 of file Flight.cpp.
Referenced by createReturnFlight().
setFlightNumber()
void Flight::setFlightNumber (const std::string & number)
Definition at line 76 of file Flight.cpp.
Referenced by createReturnFlight().
toString()
std::string Flight::toString () const
Получить строковое представление
Definition at line 173 of file Flight.cpp.
Referenced by Flight_ToString().
unloadCargoAndPassengers()
void Flight::unloadCargoAndPassengers (std::shared_ptr< Aircraft > aircraft) const
Выгрузить грузы и пассажиров по прибытии
Definition at line 166 of file Flight.cpp.
The documentation for this class was generated from the following files:
include/Flight.h
src/Flight.cpp