Система авиаперевозок (C++): Passenger Class Reference
Passenger Class Reference
Пассажир: номер, имя, аэропорты отправления/назначения; масса 80 кг.
#include <Passenger.h>
Public Member Functions
Passenger ()
Passenger (const std::string &number, const std::string &passengerName, const std::string &departure, const std::string &destination)
Passenger (const Passenger &other)
Passenger & operator= (const Passenger &other)
~Passenger ()
std::string getPassengerNumber () const
std::string getName () const
std::string getDepartureAirport () const
std::string getDestinationAirport () const
double getMass () const
Возвращает фиксированную массу 80 кг
void setPassengerNumber (const std::string &number)
void setName (const std::string &passengerName)
void setDepartureAirport (const std::string &departure)
void setDestinationAirport (const std::string &destination)
bool hasReachedDestination () const
Проверить, достиг ли пассажир места назначения
std::string toString () const
Получить строковое представление
bool isValid () const
Проверить корректность данных
bool operator== (const Passenger &other) const
bool operator!= (const Passenger &other) const
bool operator< (const Passenger &other) const
bool operator<= (const Passenger &other) const
bool operator> (const Passenger &other) const
bool operator>= (const Passenger &other) const
Detailed Description
Пассажир: номер, имя, аэропорты отправления/назначения; масса 80 кг.
Definition at line 11 of file Passenger.h.
Constructor & Destructor Documentation
Passenger() [1/3]
Passenger::Passenger ()
Definition at line 9 of file Passenger.cpp.
Referenced by operator!=(), operator<(), operator<=(), operator=(), operator==(), operator>(), operator>=(), and Passenger().
Passenger() [2/3]
Passenger::Passenger (const std::string & number, const std::string & passengerName, const std::string & departure, const std::string & destination)
Definition at line 14 of file Passenger.cpp.
Passenger() [3/3]
Passenger::Passenger (const Passenger & other)
Definition at line 21 of file Passenger.cpp.
~Passenger()
Passenger::~Passenger ()
Definition at line 38 of file Passenger.cpp.
Member Function Documentation
getDepartureAirport()
std::string Passenger::getDepartureAirport () const
Definition at line 51 of file Passenger.cpp.
getDestinationAirport()
std::string Passenger::getDestinationAirport () const
Definition at line 55 of file Passenger.cpp.
getMass()
double Passenger::getMass () const
Возвращает фиксированную массу 80 кг
Definition at line 59 of file Passenger.cpp.
getName()
std::string Passenger::getName () const
Definition at line 47 of file Passenger.cpp.
Referenced by Passenger_GetName().
getPassengerNumber()
std::string Passenger::getPassengerNumber () const
Definition at line 43 of file Passenger.cpp.
Referenced by Passenger_GetPassengerNumber().
hasReachedDestination()
bool Passenger::hasReachedDestination () const
Проверить, достиг ли пассажир места назначения
Definition at line 81 of file Passenger.cpp.
isValid()
bool Passenger::isValid () const
Проверить корректность данных
Definition at line 101 of file Passenger.cpp.
operator!=()
bool Passenger::operator!= (const Passenger & other) const
Definition at line 121 of file Passenger.cpp.
operator<()
bool Passenger::operator< (const Passenger & other) const
Definition at line 125 of file Passenger.cpp.
operator<=()
bool Passenger::operator<= (const Passenger & other) const
Definition at line 129 of file Passenger.cpp.
operator=()
Passenger & Passenger::operator= (const Passenger & other)
Definition at line 27 of file Passenger.cpp.
operator==()
bool Passenger::operator== (const Passenger & other) const
Definition at line 117 of file Passenger.cpp.
operator>()
bool Passenger::operator> (const Passenger & other) const
Definition at line 133 of file Passenger.cpp.
operator>=()
bool Passenger::operator>= (const Passenger & other) const
Definition at line 137 of file Passenger.cpp.
setDepartureAirport()
void Passenger::setDepartureAirport (const std::string & departure)
Definition at line 72 of file Passenger.cpp.
setDestinationAirport()
void Passenger::setDestinationAirport (const std::string & destination)
Definition at line 76 of file Passenger.cpp.
setName()
void Passenger::setName (const std::string & passengerName)
Definition at line 68 of file Passenger.cpp.
setPassengerNumber()
void Passenger::setPassengerNumber (const std::string & number)
Definition at line 64 of file Passenger.cpp.
toString()
std::string Passenger::toString () const
Получить строковое представление
Definition at line 89 of file Passenger.cpp.
Referenced by Passenger_ToString().
The documentation for this class was generated from the following files:
include/Passenger.h
src/Passenger.cpp