Система авиаперевозок (C++): Aircraft Class Reference
Aircraft Class Reference
Самолёт: номер, максимальная грузоподъёмность, списки грузов (обычных и срочных) и пассажиров.
#include <Aircraft.h>
Public Member Functions
Aircraft ()
Aircraft (const std::string &number, double maxPayload)
Aircraft (const Aircraft &other)
Aircraft & operator= (const Aircraft &other)
~Aircraft ()
std::string getAircraftNumber () const
double getMaxPayload () const
double getCurrentPayload () const
Получить текущую загрузку
const std::vector< std::shared_ptr< Cargo > > & getCargoList () const
const std::vector< std::shared_ptr< UrgentCargo > > & getUrgentCargoList () const
const std::vector< std::shared_ptr< Passenger > > & getPassengerList () const
void setAircraftNumber (const std::string &number)
void setMaxPayload (double maxPayload)
bool addCargo (std::shared_ptr< Cargo > cargo)
Добавить груз (возвращает true если успешно).
bool addUrgentCargo (std::shared_ptr< UrgentCargo > urgentCargo)
Добавить срочный груз
void removeCargo (const std::string &cargoNumber)
void removeUrgentCargo (const std::string &cargoNumber)
std::shared_ptr< Cargo > findCargo (const std::string &cargoNumber) const
std::shared_ptr< UrgentCargo > findUrgentCargo (const std::string &cargoNumber) const
bool addPassenger (std::shared_ptr< Passenger > passenger)
Добавить пассажира
void removePassenger (const std::string &passengerNumber)
std::shared_ptr< Passenger > findPassenger (const std::string &passengerNumber) const
bool canCarry (double additionalWeight) const
Проверить, может ли самолёт взять дополнительный груз
double getAvailableCapacity () const
Получить доступную грузоподъёмность
int getTotalPassengerCount () const
Получить общее количество пассажиров
int getTotalCargoCount () const
Получить общее количество грузов
void clearAll ()
Очистить все грузы и пассажиров
std::string toString () const
Получить строковое представление
bool isValid () const
Проверить корректность данных
std::vector< std::shared_ptr< UrgentCargo > > getOverdueCargo () const
Получить просроченные срочные грузы
std::vector< std::shared_ptr< UrgentCargo > > getUrgentCargo () const
Получить срочные грузы
Detailed Description
Самолёт: номер, максимальная грузоподъёмность, списки грузов (обычных и срочных) и пассажиров.
Definition at line 16 of file Aircraft.h.
Constructor & Destructor Documentation
Aircraft() [1/3]
Aircraft::Aircraft ()
Definition at line 8 of file Aircraft.cpp.
Referenced by Aircraft(), and operator=().
Aircraft() [2/3]
Aircraft::Aircraft (const std::string & number, double maxPayload)
Definition at line 12 of file Aircraft.cpp.
Aircraft() [3/3]
Aircraft::Aircraft (const Aircraft & other)
Definition at line 24 of file Aircraft.cpp.
~Aircraft()
Aircraft::~Aircraft ()
Definition at line 43 of file Aircraft.cpp.
Member Function Documentation
addCargo()
bool Aircraft::addCargo (std::shared_ptr< Cargo > cargo)
Добавить груз (возвращает true если успешно).
Definition at line 112 of file Aircraft.cpp.
addPassenger()
bool Aircraft::addPassenger (std::shared_ptr< Passenger > passenger)
Добавить пассажира
Definition at line 179 of file Aircraft.cpp.
addUrgentCargo()
bool Aircraft::addUrgentCargo (std::shared_ptr< UrgentCargo > urgentCargo)
Добавить срочный груз
Definition at line 126 of file Aircraft.cpp.
canCarry()
bool Aircraft::canCarry (double additionalWeight) const
Проверить, может ли самолёт взять дополнительный груз
Definition at line 213 of file Aircraft.cpp.
Referenced by addCargo(), addPassenger(), and addUrgentCargo().
clearAll()
void Aircraft::clearAll ()
Очистить все грузы и пассажиров
Definition at line 233 of file Aircraft.cpp.
findCargo()
std::shared_ptr< Cargo > Aircraft::findCargo (const std::string & cargoNumber) const
Definition at line 160 of file Aircraft.cpp.
findPassenger()
std::shared_ptr< Passenger > Aircraft::findPassenger (const std::string & passengerNumber) const
Definition at line 203 of file Aircraft.cpp.
findUrgentCargo()
std::shared_ptr< UrgentCargo > Aircraft::findUrgentCargo (const std::string & cargoNumber) const
Definition at line 169 of file Aircraft.cpp.
getAircraftNumber()
std::string Aircraft::getAircraftNumber () const
Definition at line 48 of file Aircraft.cpp.
Referenced by Aircraft_GetAircraftNumber().
getAvailableCapacity()
double Aircraft::getAvailableCapacity () const
Получить доступную грузоподъёмность
Definition at line 218 of file Aircraft.cpp.
Referenced by Aircraft_GetAvailableCapacity(), and toString().
getCargoList()
const std::vector< std::shared_ptr< Cargo > > & Aircraft::getCargoList () const
Definition at line 83 of file Aircraft.cpp.
getCurrentPayload()
double Aircraft::getCurrentPayload () const
Получить текущую загрузку
Definition at line 56 of file Aircraft.cpp.
Referenced by Aircraft_GetCurrentPayload(), canCarry(), getAvailableCapacity(), and toString().
getMaxPayload()
double Aircraft::getMaxPayload () const
Definition at line 52 of file Aircraft.cpp.
Referenced by Aircraft_GetMaxPayload().
getOverdueCargo()
std::vector< std::shared_ptr< UrgentCargo > > Aircraft::getOverdueCargo () const
Получить просроченные срочные грузы
Definition at line 259 of file Aircraft.cpp.
getPassengerList()
const std::vector< std::shared_ptr< Passenger > > & Aircraft::getPassengerList () const
Definition at line 91 of file Aircraft.cpp.
getTotalCargoCount()
int Aircraft::getTotalCargoCount () const
Получить общее количество грузов
Definition at line 228 of file Aircraft.cpp.
getTotalPassengerCount()
int Aircraft::getTotalPassengerCount () const
Получить общее количество пассажиров
Definition at line 223 of file Aircraft.cpp.
getUrgentCargo()
std::vector< std::shared_ptr< UrgentCargo > > Aircraft::getUrgentCargo () const
Получить срочные грузы
Definition at line 272 of file Aircraft.cpp.
getUrgentCargoList()
const std::vector< std::shared_ptr< UrgentCargo > > & Aircraft::getUrgentCargoList () const
Definition at line 87 of file Aircraft.cpp.
isValid()
bool Aircraft::isValid () const
Проверить корректность данных
Definition at line 254 of file Aircraft.cpp.
operator=()
Aircraft & Aircraft::operator= (const Aircraft & other)
Definition at line 31 of file Aircraft.cpp.
removeCargo()
void Aircraft::removeCargo (const std::string & cargoNumber)
Definition at line 140 of file Aircraft.cpp.
removePassenger()
void Aircraft::removePassenger (const std::string & passengerNumber)
Definition at line 193 of file Aircraft.cpp.
removeUrgentCargo()
void Aircraft::removeUrgentCargo (const std::string & cargoNumber)
Definition at line 150 of file Aircraft.cpp.
setAircraftNumber()
void Aircraft::setAircraftNumber (const std::string & number)
Definition at line 96 of file Aircraft.cpp.
setMaxPayload()
void Aircraft::setMaxPayload (double maxPayload)
Definition at line 100 of file Aircraft.cpp.
toString()
std::string Aircraft::toString () const
Получить строковое представление
Definition at line 240 of file Aircraft.cpp.
Referenced by Aircraft_ToString().
The documentation for this class was generated from the following files:
include/Aircraft.h
src/Aircraft.cpp