Система авиаперевозок (C++): FlightScheduleException Class Reference
FlightScheduleException Class Reference
Базовый класс исключений для системы расписания полётов
#include <FlightScheduleException.h>
Public Member Functions
FlightScheduleException (const std::string &msg)
Конструктор исключения
FlightScheduleException (const char *msg)
Конструктор исключения
virtual ~FlightScheduleException () noexcept=default
Деструктор
virtual const char * what () const noexcept override
Получить сообщение об ошибке
std::string getMessage () const
Получить сообщение об ошибке как строку
Detailed Description
Базовый класс исключений для системы расписания полётов
Используется для обработки ошибок, возникающих при работе с расписанием, самолётами, рейсами и другими компонентами системы.
Definition at line 17 of file FlightScheduleException.h.
Constructor & Destructor Documentation
FlightScheduleException() [1/2]
FlightScheduleException::FlightScheduleException (const std::string & msg) inline explicit
Конструктор исключения
Parameters
msg Сообщение об ошибке
Definition at line 26 of file FlightScheduleException.h.
Referenced by InvalidAircraftException::InvalidAircraftException(), and InvalidAircraftException::InvalidAircraftException().
FlightScheduleException() [2/2]
FlightScheduleException::FlightScheduleException (const char * msg) inline explicit
Конструктор исключения
Parameters
msg Сообщение об ошибке (C-строка)
Definition at line 32 of file FlightScheduleException.h.
~FlightScheduleException()
virtual FlightScheduleException::~FlightScheduleException () virtual default noexcept
Деструктор
Member Function Documentation
getMessage()
std::string FlightScheduleException::getMessage () const inline
Получить сообщение об ошибке как строку
Returns
Строка с сообщением об ошибке
Definition at line 51 of file FlightScheduleException.h.
what()
virtual const char * FlightScheduleException::what () const inline override virtual noexcept
Получить сообщение об ошибке
Returns
C-строка с сообщением об ошибке
Definition at line 43 of file FlightScheduleException.h.
Referenced by what().
The documentation for this class was generated from the following file:
include/FlightScheduleException.h