Система авиаперевозок (C++): Airport Class Reference
Airport Class Reference
Аэропорт: название и контейнеры грузов, пассажиров и самолётов.
#include <Airport.h>
Public Member Functions
Airport ()
Airport (const std::string &airportName)
Airport (const Airport &other)
Airport & operator= (const Airport &other)
~Airport ()
std::string getName () const
const std::vector< std::shared_ptr< Cargo > > & getCargoList () const
const std::vector< std::shared_ptr< UrgentCargo > > & getUrgentCargoList () const
const std::vector< std::shared_ptr< Passenger > > & getPassengerList () const
const std::vector< std::shared_ptr< Aircraft > > & getAircraftList () const
void setName (const std::string &airportName)
void addCargo (std::shared_ptr< Cargo > cargo)
void addUrgentCargo (std::shared_ptr< UrgentCargo > urgentCargo)
void removeCargo (const std::string &cargoNumber)
void removeUrgentCargo (const std::string &cargoNumber)
std::shared_ptr< Cargo > findCargo (const std::string &cargoNumber) const
std::shared_ptr< UrgentCargo > findUrgentCargo (const std::string &cargoNumber) const
void addPassenger (std::shared_ptr< Passenger > passenger)
void removePassenger (const std::string &passengerNumber)
std::shared_ptr< Passenger > findPassenger (const std::string &passengerNumber) const
void addAircraft (std::shared_ptr< Aircraft > aircraft)
void removeAircraft (const std::string &aircraftNumber)
std::shared_ptr< Aircraft > findAircraft (const std::string &aircraftNumber) const
double getTotalCargoWeight () const
Получить общий вес всех грузов
int getTotalPassengerCount () const
Получить общее количество пассажиров
int getTotalAircraftCount () const
Получить общее количество самолётов
std::string toString () const
Получить строковое представление
bool isValid () const
Проверить корректность данных
std::vector< std::shared_ptr< UrgentCargo > > getOverdueCargo () const
Получить просроченные срочные грузы
std::vector< std::shared_ptr< UrgentCargo > > getUrgentCargo () const
Получить срочные грузы
Detailed Description
Аэропорт: название и контейнеры грузов, пассажиров и самолётов.
Definition at line 18 of file Airport.h.
Constructor & Destructor Documentation
Airport() [1/3]
Airport::Airport ()
Definition at line 8 of file Airport.cpp.
Referenced by Airport(), and operator=().
Airport() [2/3]
Airport::Airport (const std::string & airportName)
Definition at line 12 of file Airport.cpp.
Airport() [3/3]
Airport::Airport (const Airport & other)
Definition at line 16 of file Airport.cpp.
~Airport()
Airport::~Airport ()
Definition at line 35 of file Airport.cpp.
Member Function Documentation
addAircraft()
void Airport::addAircraft (std::shared_ptr< Aircraft > aircraft)
Definition at line 143 of file Airport.cpp.
addCargo()
void Airport::addCargo (std::shared_ptr< Cargo > cargo)
Definition at line 66 of file Airport.cpp.
addPassenger()
void Airport::addPassenger (std::shared_ptr< Passenger > passenger)
Definition at line 117 of file Airport.cpp.
addUrgentCargo()
void Airport::addUrgentCargo (std::shared_ptr< UrgentCargo > urgentCargo)
Definition at line 72 of file Airport.cpp.
findAircraft()
std::shared_ptr< Aircraft > Airport::findAircraft (const std::string & aircraftNumber) const
Definition at line 159 of file Airport.cpp.
findCargo()
std::shared_ptr< Cargo > Airport::findCargo (const std::string & cargoNumber) const
Definition at line 98 of file Airport.cpp.
findPassenger()
std::shared_ptr< Passenger > Airport::findPassenger (const std::string & passengerNumber) const
Definition at line 133 of file Airport.cpp.
findUrgentCargo()
std::shared_ptr< UrgentCargo > Airport::findUrgentCargo (const std::string & cargoNumber) const
Definition at line 107 of file Airport.cpp.
getAircraftList()
const std::vector< std::shared_ptr< Aircraft > > & Airport::getAircraftList () const
Definition at line 56 of file Airport.cpp.
getCargoList()
const std::vector< std::shared_ptr< Cargo > > & Airport::getCargoList () const
Definition at line 44 of file Airport.cpp.
getName()
std::string Airport::getName () const
Definition at line 40 of file Airport.cpp.
Referenced by Airport_GetName().
getOverdueCargo()
std::vector< std::shared_ptr< UrgentCargo > > Airport::getOverdueCargo () const
Получить просроченные срочные грузы
Definition at line 225 of file Airport.cpp.
getPassengerList()
const std::vector< std::shared_ptr< Passenger > > & Airport::getPassengerList () const
Definition at line 52 of file Airport.cpp.
getTotalAircraftCount()
int Airport::getTotalAircraftCount () const
Получить общее количество самолётов
Definition at line 202 of file Airport.cpp.
getTotalCargoWeight()
double Airport::getTotalCargoWeight () const
Получить общий вес всех грузов
Definition at line 169 of file Airport.cpp.
Referenced by toString().
getTotalPassengerCount()
int Airport::getTotalPassengerCount () const
Получить общее количество пассажиров
Definition at line 197 of file Airport.cpp.
getUrgentCargo()
std::vector< std::shared_ptr< UrgentCargo > > Airport::getUrgentCargo () const
Получить срочные грузы
Definition at line 238 of file Airport.cpp.
getUrgentCargoList()
const std::vector< std::shared_ptr< UrgentCargo > > & Airport::getUrgentCargoList () const
Definition at line 48 of file Airport.cpp.
isValid()
bool Airport::isValid () const
Проверить корректность данных
Definition at line 220 of file Airport.cpp.
operator=()
Airport & Airport::operator= (const Airport & other)
Definition at line 23 of file Airport.cpp.
removeAircraft()
void Airport::removeAircraft (const std::string & aircraftNumber)
Definition at line 149 of file Airport.cpp.
removeCargo()
void Airport::removeCargo (const std::string & cargoNumber)
Definition at line 78 of file Airport.cpp.
removePassenger()
void Airport::removePassenger (const std::string & passengerNumber)
Definition at line 123 of file Airport.cpp.
removeUrgentCargo()
void Airport::removeUrgentCargo (const std::string & cargoNumber)
Definition at line 88 of file Airport.cpp.
setName()
void Airport::setName (const std::string & airportName)
Definition at line 61 of file Airport.cpp.
toString()
std::string Airport::toString () const
Получить строковое представление
Definition at line 207 of file Airport.cpp.
Referenced by Airport_ToString().
The documentation for this class was generated from the following files:
include/Airport.h
src/Airport.cpp